name: venturo_core
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  cached_network_image: ^3.4.0
  carousel_slider: ^5.0.0
  change_app_package_name: ^1.1.0
  connectivity_plus: ^6.1.3
  cupertino_icons: ^1.0.2
  dio: ^5.8.0+1
  dot_navigation_bar: ^1.0.2
  fast_rsa: ^3.6.1
  flutter:
    sdk: flutter
  flutter_custom_clippers: ^2.1.0
  flutter_easyloading: ^3.0.5
  flutter_inappwebview: null
  flutter_screenutil: ^5.9.0
  get: ^4.6.6
  google_fonts: ^6.2.0
  google_nav_bar: ^5.0.7
  hive_flutter: ^1.1.0
  intl: ^0.20.2
  logger: ^2.5.0
  panara_dialogs: ^0.1.5
  sentry_flutter: ^7.18.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
